import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import { SocketProvider } from '@/contexts/socketContext'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Talk to me',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${rubik.className} bg-800 text-white`}>
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  )
}
